//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyrsach
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepertoireTeatra
    {
        public int Performance_IDD { get; set; }
        public int Tour_IDD { get; set; }
        public System.DateTime PeriodEvent { get; set; }
        public System.DateTime DaysTimes { get; set; }
        public string TicketPrice { get; set; }
    
        public virtual Performance Performance { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
