//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyrsach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Troupe
    {
        public int Troupe_ID { get; set; }
        public int Worker_IDD { get; set; }
        public int Actors { get; set; }
        public string NameRole { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Performance_IDD { get; set; }
    
        public virtual Employees_of_the_teatr Employees_of_the_teatr { get; set; }
        public virtual Performance Performance { get; set; }
    }
}
